"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-14 19:56:14.619318
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "closures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("closure_date", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_closures")),
        sa.UniqueConstraint("closure_date", name=op.f("uq_closures_closure_date")),
    )
    op.create_table(
        "daily_specials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("special_date", sa.Text(), nullable=False),
        sa.Column("dish_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price_brl", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_specials")),
        sa.UniqueConstraint(
            "special_date", "dish_name", name=op.f("uq_daily_specials_special_date")
        ),
    )
    with op.batch_alter_table("daily_specials", schema=None) as batch_op:
        batch_op.create_index("idx_specials_date", ["special_date"], unique=False)

    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("customer_name", sa.Text(), nullable=False),
        sa.Column("customer_phone", sa.Text(), nullable=False),
        sa.Column("customer_email", sa.Text(), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("reservation_date", sa.Text(), nullable=False),
        sa.Column("start_time", sa.Text(), nullable=False),
        sa.Column("end_time", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('CONFIRMADA', 'CANCELADA', 'CONCLUIDA', 'NO_SHOW')",
            name=op.f("ck_reservations_status"),
        ),
        sa.CheckConstraint("party_size BETWEEN 1 AND 12", name=op.f("ck_reservations_party_size")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
        sa.UniqueConstraint("code", name=op.f("uq_reservations_code")),
    )
    with op.batch_alter_table("reservations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_reservations_date_status", ["reservation_date", "status"], unique=False
        )

    op.create_table(
        "service_hours",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("opens_at", sa.Text(), nullable=False),
        sa.Column("closes_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "service IN ('almoco', 'jantar')", name=op.f("ck_service_hours_service")
        ),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_service_hours_weekday")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_hours")),
        sa.UniqueConstraint("weekday", "service", name=op.f("uq_service_hours_weekday")),
    )
    op.create_table(
        "tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("zone", sa.Text(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("combinable", sa.Boolean(), nullable=False),
        sa.Column("reservable", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "zone IN ('salao', 'varanda', 'mezanino', 'balcao')", name=op.f("ck_tables_zone")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tables")),
        sa.UniqueConstraint("label", name=op.f("uq_tables_label")),
    )
    op.create_table(
        "reservation_tables",
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_tables_reservation_id_reservations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["tables.id"], name=op.f("fk_reservation_tables_table_id_tables")
        ),
        sa.PrimaryKeyConstraint("reservation_id", "table_id", name=op.f("pk_reservation_tables")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservation_tables")
    op.drop_table("tables")
    op.drop_table("service_hours")
    with op.batch_alter_table("reservations", schema=None) as batch_op:
        batch_op.drop_index("idx_reservations_date_status")

    op.drop_table("reservations")
    with op.batch_alter_table("daily_specials", schema=None) as batch_op:
        batch_op.drop_index("idx_specials_date")

    op.drop_table("daily_specials")
    op.drop_table("closures")
    # ### end Alembic commands ###
